### ISSUE TITLE
Add react-intl provider to App

### ISSUE THREAD

**Issue by atparkweb** [juliwithoutthee/mymizu-web#1]

**Comment by quesiu** [comment]
[react-intl official documentation](https://formatjs.io/docs/getting-started/installation/)
[Step-by-step guide React with i18n](https://lokalise.com/blog/react-i18n-intl/)
[How to translate React app with react-intl (Example)](https://www.codeandweb.com/babeledit/tutorials/how-to-translate-your-react-app-with-react-intl)
