### ISSUE TITLE
Fun Fact Component

### ISSUE THREAD

**Issue by juliwithoutthee** [juliwithoutthee/mymizu-web#4]
React component to generate random facts

**Comment by quesiu** [comment]
English
- 740 plastic bottles are bought in Japan every second.
- More than 8 million tons of plastic are dumped into our oceans every year.
- Approximately 2 million plastic bags are used every minute around the world.
- The average plastic bag is used for only 12 minutes!
- Global plastic production has doubled in the past 50 years.
- It's estimated that 50% of the plastic we consume is used just once and thrown away.
- Approximately 90 percent of all trash floating on the ocean's surface is plastic, with 46,000 pieces of plastic per square mile.
- There are over 5 trillion pieces of plastic in our oceans – enough to circle the Earth over 400 times.
- Japan is the world's second-biggest producer per capita of plastic waste behind the U.S.
- Over 25 billion PET bottle products are produced every year in Japan, equal to approximately 180 bottles per person.
- By 2050, it is estimated that there will be more plastic than fish in the sea.

**Comment by quesiu** [comment]
Japanese

- 日本では1秒間に740本のペットボトルが買われています。
- 海には毎年800万トン以上のプラスチックが捨てられています。
- 世界では1分間に約200万枚のレジ袋が使用されています。
- 平均的なレジ袋の使用時間は、わずか12分です
- 世界のプラスチック生産量は、過去50年間で2倍になりました。
- 消費するプラスチックの50％は、一度だけ使用されて捨てられていると言われています。
- 海面に浮かぶゴミの約90％がプラスチックで、1平方マイルあたり46,000個のプラスチックがあります。
- 海には5兆個以上のプラスチックがあり、これは地球を400回以上一周するのに十分な量です。
- 日本は、一人当たりのプラスチック廃棄物排出量が米国に次いで世界第2位です。
- 日本では年間250億本以上のペットボトル製品が生産されており、これは一人当たり約180本のペットボトルに相当します。
- 2050年には、海の中の魚の数よりプラスチックの方が多くなると言われています。
